pfnet/pfio

- setup.py
Reverts chainer/chainerio#5 since it introduces a bug into setup.py, will add it after the activation of CI
> Revert "Add classifiers and keywords to setup.py"

- tests/test_context.py
This commit adds tests to verify if the fs detection also works when we
deal with containers.
for example:
"file://some/container.zip"
"hdfs:///another/container.zip"
This PR solves #11
> Add fs detection test on containers

- CHANGELOG.md
This commit revert the change to add CHANGELOG.md.
We keep change logs in the release logs to match the chainer style.
> Remove CHANGELOG

- docs/Makefile
- docs/source/conf.py
- docs/source/design.rst
This commit fixes the following bugs which fail the API documentation
build using sphinx.
1. Enforce the error check. Fail the build when sphinx generates any
warning. This is because sphinx considers import failure as warning,
which it should be an error and fail the build.
2. Fix import error. Fix the wrong sys.path to include the `ChainerIO`
itself, and uses mock to include `Chainer`.
3. Fix some warning/error in the links
> Bugfix for sphinx

- chainerio/containers/zip.py
- chainerio/filesystems/hdfs.py
- chainerio/profiler/io_profiler.py
Directly calling `logging.{debug,info,...}` is known to cause of strange behaviors of other loggers outside the module, therefore it is suggested not to do so when developing a library.
> For libraries that want to perform logging, you should create a dedicated logger object,and initially configure it as follows:
> ```
> # somelib.py
> importlogging
> log = logging.getLogger(__name__)
> log.addHandler(logging.NullHandler())
> ```
> -- _Python Cookbook 3rd edition pp. 558_
>     _https://d.cxcore.net/Python/Python_Cookbook_3rd_Edition.pdf_
What is actually wrong with the root logger use?
The below short code snippet is a minimum explanation of a typical phenomenon (py3.6.7).
Exactly the same thing happened to me when using chainerio in my application code that also uses Python logging …
> Not to use the root logger, to prevent affecting to loggers outside chainerio

- setup.py
This commit changes the supported python version from 3.5 to 3.5.3
A bug in type hint in Python 3.5.2, which cause the chainerio to raise error,
was fixed 3.5.3
For more details, please see
https://stackoverflow.com/questions/42942867/optionaltypefoo-raises-typeerror-in-python-3-5-2
This closes #28
> Change the supported python version to 3.5.3

- chainerio/__init__.py
- chainerio/containers/zip.py
- chainerio/io.py
- tests/container_tests/test_zip_container.py
This PR add recursive parameter to `list` API and implement `recursive in zip`.
This PR solves the first to-do in #46 and #43.
> Add recursive to zip list

- chainerio/filesystems/hdfs.py
This PR improves the pickle performance described in #42. closes #42.
In order to add the missing `peek` support, the HdfsFile object gets
wrapped with `io.BufferedReader` when opening with 'rb',
which is how the file is opened when using pickle.
Before (from #42) :
```
$ python test.py
chainerio:  186.07044076919556
```
with this PR
```
$ python test.py
chainerio:  47.654032945632935
```
> Improve pickle performance on HDFS

- chainerio/containers/zip.py
- tests/container_tests/test_zip_container.py
This PR adds nested zip support for Python< 3.7.
As described in #41, Unlike the Python > 3.7, due to implementation issues in Python,
the nested zip support is not enabled by default.
This PR introduces a workaround to enable nested zip access in Python <3.7 as follow:
When accessing nested zip with Python< 3.7, the whole nested zip file is read and put into a `BytesIO` object to add `seekable` to the file object to create the corresponding `ZipFile` object. 
This workaround can introduce performance and memory consumption issues when the nested zip file is huge and a small portion of the nested zip is actually needed.
A warning message is generated in that case.
Tests for nested zip are also added in this PR.
This PR solves the 2nd problem in #37, i.e. #41.
> Nested Zip Support for Python<3.7

- docs/source/design.rst
This commit fixes an outdated example from using `namelist` to Usenet
`list(recursive=True)` to list all the files in a zip.
> Fix an outdated example

- chainerio/filesystems/hdfs.py
- tests/filesystem_tests/test_hdfs_handler.py
This PR adds recursive support to list in HDFS to align with the API.
This PR solves the 2nd todo in #46
> Add recursive support to list in hdfs

- chainerio/__init__.py
- chainerio/filesystems/posix.py
- tests/filesystem_tests/test_posix_handler.py
- tests/test_context.py
This PR adds recursive mode to list in posix. This resolve the third todo in #46.
> Add recursive option to POSIX filesystem handler

- chainerio/__init__.py
- chainerio/io.py
- docs/source/reference.rst
This commit adds doc strings to all the public APIs for chainerio
in `__init__.py`, which also is a superset of APIs in the `io.py`
This closes #55
This closes #52
> Add doc strings to public API

- tests/container_tests/test_zip_container.py
- tests/filesystem_tests/test_posix_handler.py
- tests/test_context.py
This PR makes use of the `TempDirectory` to create random temp directory
for each test, and resolve the test failure due some leftover from
previous failed tests.
This PR closes #62
> Use TempDirectory for tests

- chainerio/filesystems/hdfs.py
- tests/filesystem_tests/test_hdfs_handler.py
This PR changes to `klist` to get the default principal username from
the default keytab, instead of using the current login username, since
these two sometimes are different.
I have checked Python wrapper of kerberos like 
https://pypi.org/project/python-krbV/
https://pypi.org/project/kerberos/
they are either not maintained or does not support to get the username from keytab
This closes #50
> Use `klist` to get the username from kerberos

- chainerio/containers/zip.py
- tests/container_tests/test_zip_container.py
This PR fixes the two bugs mentioned in #66
Closes #66
> Bugfix list zip

- .pfnci/docker/Dockerfile
- .pfnci/docker/install.sh
- .pfnci/test.sh
Add Python 3.5.2 test into docker and test script. The Python 3.5.2 replaces the 3.5.8 test as tox does not support specifying micro version. 
Downgrade the base docker image from ubuntu:18.04 to ubuntu:16.04
as 18.04 only support openssl 1.1.0 which does not work with Python
3.5.2.
This closes #74
> Add Python 3.5.2 test to CI

- chainerio/containers/zip.py
- tests/container_tests/test_zip_container.py
This PR limits the files to whose are under the given `path_or_prefix`
when using recursive list in zip.
The `path_or_prefix` was ignored before and simply dumped all the files in
recursive list.
This closes #72
> Bugfix for recursive list with `path_or_prefix` in zip

- chainerio/containers/zip.py
- tests/container_tests/test_zip_container.py
This commit adds non-trailing-slash support to directories to stat of
zip.
The code is mainly from the TODO in #68 
Solves Problem 2 in #67.
> Support of directories without trailing slash in `stat` of zip

- chainerio/containers/zip.py
- tests/container_tests/test_zip_container.py
This PR adds non-trailing-slash support to directories to `exists` of
zip.
Solves Problem 4 in #67.
> Support of directories without trailing slash in `exists` of zip 

- tests/container_tests/test_zip_container.py
We avoid using `shutil.make_archive` to create the test zip file as the
`shutil.make_archive` introduced an inconsistent behavior between versions
when creating the zip file. For more details, please refer to
https://bugs.python.org/issue28488
In this PR, we switch our own make_zip to create the zip.
> Avoid make_archive in the test_zip_container

- tests/container_tests/test_zip_container.py
This commit adds non-trailing-slash test to directories to `isdir` of
zip.
Solves Problem 1 in #67. 
This depends on #70
> Add tests of directories without trailing slash in `isdir` of zip

- tests/container_tests/test_zip_container.py
This commit fixes a bug caused by a outdated variable name in
test_zip_container.
> Fix a bug in test_zip_container

- chainerio/__init__.py
- chainerio/_context.py
- tests/test_context.py
This PR add scheme checks to the beginning of `create_handler`, and
raises ValueError when the scheme is not supported.
This PR closes #86.
> Check for the supported scheme in `create_handler`

- chainerio/_context.py
- tests/test_context.py
The current, `fs_handler_list` cached the handler.
This PR removes the cache and returns a new handler each time
`create_handler` is called.
This PR solves #87.
> Return new handler when calling `create_handler`

- chainerio/containers/zip.py
- tests/container_tests/test_zip_container.py
This PR normalizes the input path first before any process in zip `stat`.
This PR solves a part of issue #75.
> Normalize input path in zip `stat`

- chainerio/containers/zip.py
- tests/container_tests/test_zip_container.py
This PR normalizes the input path first before any process in zip `exists`.
This PR solves a part of issue #75.
> Normalize input path in zip `exists`

- chainerio/containers/zip.py
- tests/container_tests/test_zip_container.py
This PR normalizes the input path first before any process in zip
open.
This PR solves a part of issue #75.
> Normalize input path in zip `open`

- chainerio/cache/file_cache.py
- docs/source/reference.rst
- tests/cache_tests/test_file_cache.py
By letting developers explicitly call `perserve()` method, the cache knows when to freeze the data. This change resolve the issue that cached data can't be reused across the training session (thus re-constructing the cache by re-reading data from remote storage), limiting the use cases to only same number & configuration of cached data.
See `tests/cache_tests/test_file_cache.py` for possible example usage.
> Add persistence to cache.FileCache

- chainerio/containers/zip.py
- tests/container_tests/test_zip_container.py
The `isdir` simply forwards the input to `stat` and relies on `stat`
to normalize the input path.
To align with the behavior of `os.path.isdir`, False is returned when
the given file or directory does not exist.
> Normalize input path in zip `isdir`

- tests/filesystem_tests/test_hdfs_handler.py
This PR removes an out-of-date HDFS test.
This PR closes #94
> Bugfix: remove out-of-date tests

- chainerio/filesystems/hdfs.py
- setup.py
This commit changes to use krbticket 1.0.2 to avoid issues when the
KRB5_KTNAME is not given.
This PR should be tested after #95
> Move to krbticket 1.0.2

- chainerio/filesystems/hdfs.py
- docs/source/reference.rst
- tests/filesystem_tests/test_hdfs_handler.py
This commit fixes a bug where the principal name is not obtained
correctly when a keytab is given though KRB5_KTNAME
This closes #93 
This should be tested after #96
> Bugfix: get correct principal name when keytab is given

- chainerio/filesystems/hdfs.py
- setup.py
To avoid kerberos ticket name issues when using multiprocessing.
> Update to krbticket 1.0.3

- chainerio/containers/zip.py
- tests/container_tests/test_zip_container.py
This PR solves `ZipContainer` issue in https://github.com/chainer/chainerio/issues/104
> check pid in zip

- tests/filesystem_tests/test_hdfs_handler.py
This PR fixes HDFS unittests.
The following error occurred on the current master branch.
```
================================================================================================================ FAILURES ================================================================================================================
______________________________________________________________________________________________________ TestHdfsHandler.test_exists _______________________________________________________________________________________________________
self = <test_hdfs_handler.TestHdfsHandler testMethod=test_exists>
def test_exists(self):
non_exist_file = "non_exist_file.txt"
with chainerio.create_handler(self.fs) as handler:
> …
```
> Fix HDFS unittests

- .pfnci/docker/Dockerfile
- chainerio/containers/zip.py
- setup.py
- tests/container_tests/test_zip_container.py
This PR fixes a bug which is related to non-directory-included zip, a
kind of zip that contains hierarchical structure but does not contain
the directories themselves. Such kind of zip can be made with "zip -D".
This PR fixes the bug when list or isdir to these "non-exist" directory
in such non-directory-included zip.
We do NOT handle the `exists` in this case as the directories do NOT `exist` **physically**
in the zip, but **logically** `exist`, we want to be honest on what is here and what is not. Also it helps to prevent users from accessing the `stat` of these kind of directory
> Bugfix: list and isdir for non-directory-included zip

- tests/container_tests/test_zip_container.py
This PR refactors the test_zip_container, changes it from using the for
loop thought multiple test cases, to use the `parameterized` package for
better bug identification.
> Refactoring: Change to parameterized

- pfio/__init__.py
- pfio/io.py
This PR replaces all the occurrences of 'an URI' with 'a URI' in the comments.
Because URI is not an acronym, typically 'a URI' is used.
> Replace 'an URI' with 'a URI'

- README.md
- pfio/__init__.py
- pfio/_typing.py
- pfio/io.py
- setup.py
I noticed that `github.com/chainer/pfio` remains in several places while the repository has moved to `github.com/pfnet/pfio`.
> replace 'github.com/chainer/pfio' with 'github.com/pfnet/pfio'

- .pfnci/test.sh
- tests/filesystem_tests/test_hdfs_handler.py
numpy >= 1.14 is used when building the documentation. It requires
python >= 3.6, which causes an error in the current CI. This PR fixes
the python version to 3.7 when testing the documentation.
For more details: https://ci.preferred.jp/chainerio/60833/
> Test documentation with python 3.7

- pfio/filesystems/hdfs.py
- setup.py
This PR removes the `krbticket`. The `krbticket` was introduced to
update the kerberos ticket. As the `Hadoop` handles the ticket update
internally, we have decided to remove the `krbticket` and rely on the
`Hadoop` update mechanism.
> Remove `krbticket`

- docs/source/reference.rst
- pfio/__init__.py
- pfio/cache/__init__.py
- pfio/cache/file_cache.py
- pfio/cache/multiprocess_file_cache.py
- tests/cache_tests/test_cache.py
- tests/cache_tests/test_file_cache.py
- tests/cache_tests/test_multiprocess_file_cache.py
In case we combine pfio (+HDFS) with PyTorch DataLoader (num_workers>0), due to the following
reasons that are complexly related each other, I noticed that it is hard to make efficient/effective use of pfio FileCache easily.
* With HDFS, setting num_workers>0 is necessary for practical data loading performance
* The current pfio FileCache supports therad-safety but cannot be process-safe
* Currently PyTorch DataLoader is designed to destroy all the worker processes at the end of each epoch
https://github.com/pytorch/pytorch/pull/35795 would solve part of the problems, but being difficult for efficiently setting higher `num_workers` will remain unsolved.
After serious considerations, I figured out that implementing multi-process safe file cache is the simplest way to overcome this issue. …
> MultiprocessFileCache for efficient and easy cache with pytorch dataloader (num_workers>0)

- setup.py
I failed to install `pfio` on fresh Python environment (`ModuleNotFoundError: No module named 'six'`).
pfio uses `six` but it is not listed in the dependency.
> Add six to install dependency

- pfio/cache/file_cache.py
- pfio/cache/multiprocess_file_cache.py
- tests/cache_tests/test_cache.py
Currently, pfio caches check the index of `get` and `put` by the following ways.
- FileCache/MultiprocessFileCache: simple assertion (0 <= i < N)
- NaiveCache: IndexError (i < N; based on the list inside)
In PyTorch, when iterating over a Dataset _without DataLoader_ (which is actually rare case), it doesn't respect the length (`__len__`) of the dataset but instead detects the termination by either IndexError or StopIteration.
```python
>>> import torch
>>>
>>> class Foo1(torch.utils.data.Dataset):
...     def __len__(self):
...         return 3
...     def __getitem__(self, i):
...         print(i)
...         assert 0 <= i < 3
...         return i
... 
>>> class Foo2(torch.utils.data.Dataset):
...     def __len__(self):
...         return 3
...     def __getitem__(self, i):
... …
```
> Cache index error

- pfio/cache/file_cache.py
- pfio/cache/multiprocess_file_cache.py
- tests/cache_tests/test_cache.py
- tests/cache_tests/test_multiprocess_file_cache.py
This PR introduces size limitation (in bytes) of cache data file in `FileCache` and `MultiprocessFileCache`.
Since the file caches are essentially to make a local copy of the entire dataset, they can easily run out of local disk accidentally.
In order to deal with it, the current file caches already handle `errno=ENOSPC` properly, i.e., even when disk full it does not die but just warn without adding the data.
However in some situations this might not be sufficient:
- We basically want to always keep sufficient amount of free space in local (say, GBs) for system stability
- In kubernetes environment, a pod which runs out of local disk will be Evicted (=killed) *before actually getting ENOSPC*
In this PR, the `cache_size_limit` option is added to `FileCache` and `MultiprocessFileCache` …
> Introduce size limit to file caches

- pfio/cache/file_cache.py
- pfio/cache/multiprocess_file_cache.py
- tests/cache_tests/test_cache.py
- tests/cache_tests/test_file_cache.py
- tests/cache_tests/test_multiprocess_file_cache.py
Currently file caches (FileCache and MultiprocessFileCache) save the cache information separately into index file and data file.
This PR is to propose to change it to single file.
The new cache file is formatted as:
- index part: (8 bytes sample offset + 8 bytes sample size) * N
- data part: (arbitrary size of binary data) * N
where N is the number of samples to cache.
This is actually completely equivalent to just concatenating the current index and data file.
#143 will introduce limitation of cache data, however currently it is limited to data file only.
It is usually OK - as the index files are relatively negligible in most cases (e.g., ImageNet1K case 34GB vs 20MB), but as the number of parallelism grows the index file increases, which becomes relatively non-trivial, but they'll be …
> Single cache file

- chainerio/__init__.py
- docs/source/index.rst
- docs/source/v2.rst
- pfio/chainer_extensions/__init__.py
- pfio/io.py
- pfio/testing/__init__.py
- pfio/v2/__init__.py
- pfio/v2/fs.py
- pfio/v2/hdfs.py
- pfio/v2/local.py
- pfio/v2/s3.py
- pfio/v2/zip.py
- setup.py
- tests/v2_tests/test_fs.py
- tests/v2_tests/test_hdfs.py
- tests/v2_tests/test_local.py
- tests/v2_tests/test_zip.py
I've drafted a new API to solve existing issues that stem from API design. Partial AWS S3 API support is also added.
(copy from doc)
PFIO v2 API tries to solve the impedance mismatch between different
local filesystem, NFS, and other object storage systems, with a lot
simpler and cleaner code.
It has removed several toplevel functions that seem to be less
important. It turned out that they introduced more complexity than
originally intended, due to the need of the global context. Thus,
functions that depends on the global context such as ``open()``,
``set_root()`` and etc. have been removed in v2 API.
Instead, v2 API provides only two toplevel functions that enable
direct resource access with full URL: ``open_url()`` and
``fs.from_url()``. The former opens a file and returns FileObject. …
> File access V2 API

- pfio/v2/local.py
V2 API partly addresses #61 by adding trailing slash to directories by default, but introduced a bug.
> Don't add trailing slash to files

- pfio/v2/s3.py
Some function (e.g., `torch.save`) invoke `flush` method explicitly. But `_ObjectWriter` in s3.py raises `ValueError: ('I/O operation on uninitialized object')` because flush is not supported in S3.
This PR overwrites `flush` method to avoid the above exception.
> Overwrite flush method of ObjectWriter in s3.py

- pfio/v2/s3.py
- tests/v2_tests/test_fs.py
- tests/v2_tests/test_s3.py
`last_modified` attribute in `S3ObjectStat` is datetime, while Local fs's `last_modified` attribute is floating point value.
> Fix last_modified attr in S3ObjectStat

- pfio/cache/file_cache.py
- pfio/cache/multiprocess_file_cache.py
- pfio/testing/__init__.py
- tests/cache_tests/test_file_cache.py
It requires `stat(1)` which is included in GNU coreutils. I think we can assume it.
> No use of NFS for file cache

- pfio/testing/__init__.py
The line `import mock` depends the _mock_ module from PyPI, so it also requires users to take care of an additional package installation.
It seems that this was installed at same time with some other dependencies so far; but now this line causes `ModuleNotFoundError: No module named 'mock'`.
Python provides _unittest.mock_ modules as the standard library from Python 3.3+ and this is compatible with the _mock_ module as a backport. This PR replaces `import mock` to `from unittest import mock` (revised version of #176).
> Use unittest.mock instead

- pfio/v2/s3.py
- tests/v2_tests/test_s3.py
This PR adds _checkfork() in S3.open to prevent function call under a multiprocessing situation. Fixes #174.
> Add _checkfork() in S3.open as a foolproof (fix #174)

- pfio/testing/__init__.py
- pfio/v2/s3.py
- tests/v2_tests/test_fs.py
@HiroakiMikami reported that loading a JSON file caused an error like this:
```
File "/home/kota/.local/lib/python3.6/site-packages/botocore/response.py", line 77, in read
chunk = self._raw_stream.read(amt)
File "/home/kota/.local/lib/python3.6/site-packages/urllib3/response.py", line 519, in read
data = self._fp.read(amt) if not fp_closed else b""
File "/usr/lib/python3.6/http/client.py", line 448, in read
b = bytearray(amt)
ValueError: negative count
```
This is due to calling `.read(-1)` to S3 file object [directly passes `-1` to S3 StreamBody object](https://github.com/pfnet/pfio/blob/1.4.0/pfio/v2/s3.py#L60) . But S3 streambody doesn't accept negative integer, passing it directly to HTTP stream.
This change is a hotfix for 1.4.0.
Also, testing with `mock_s3` did not reproduce this …
> Fix read(-1) call from S3 StreamBody

- pfio/v2/s3.py
- tests/v2_tests/test_fs.py
@HiroakiMikami reported a bug where `readlines()` raises an undefined error.
```python
s3 = pfio.v2.S3(bucket)
with s3.open(os.path.join(prefix, "train.csv"), "r") as file:
print(list(file.readlines()))
```
leads to 
```python
File "preprocess/launcher/create_task_spec.py", line 62, in <module>
main()
File "preprocess/launcher/create_task_spec.py", line 58, in main
run(seed, n_repository, bucket, prefix)
File "preprocess/launcher/create_task_spec.py", line 16, in run
print(list(file.readlines()))
File "/foo/bar/python3.8/site-packages/pfio/v2/s3.py", line 50, in read
r = 'bytes={}-{}'.format(s, e)
UnboundLocalError: local variable 'e' referenced before assignment
```
> Fix text mode readlines

- pfio/v2/s3.py
Didn't happen with moto==2.0, but with 2.2.6.
```
tests/v2_tests/test_s3.py:59:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <pfio.v2.s3._ObjectWriter object at 0x7f7598a5eb80>
def close(self):
if len(self.parts) == 0:
self.client.put_object(Body=self.buf.getvalue(),
Bucket=self.bucket,
Key=self.key)
else:
self._flush()
c = self.client
max_parts = len(self.parts)
res = c.list_parts(Bucket=self.bucket,
Key=self.key,
UploadId=self.mpu_id, MaxParts=max_parts)
if res['IsTruncated']:
>               raise RuntimeError('truncated.')
E               RuntimeError: truncated.
pfio/v2/s3.py:197: RuntimeError
```
> Fix off-by-one unit test failure

- .readthedocs.yaml
From RTFD:
```
Error
Problem in your project's configuration. Invalid "formats": expected one of (htmlzip, pdf, epub), got html
```
> Fix RTFD build

- pfio/v2/s3.py
- tests/v2_tests/test_s3.py
S3.list method returns relative path of the content keys, but returns entire key of the common-prefixes.
This PR make the API return relative path of the common prefixes.
> Fix bug in S3.list

- pfio/v2/fs.py
- pfio/v2/hdfs.py
- pfio/v2/local.py
- tests/v2_tests/test_fs.py
> Add `force_type` option to from_url

- pfio/v2/s3.py
- tests/v2_tests/test_s3.py
Currently, S3 does not imitate directory. Thus, we have to branch code based on the filesystem when handling directories with `pfio`.
This PR handles common prefixes that end with "/" as directories in `S3` to increase compatibility between `FileSystem`s.
> Treat prefix ending with "/" as directory

- loader-bench/README.md
- loader-bench/main.py
- loader-bench/requirements.txt
- setup.py
Add benchmark to compare cache class performance
```sh
$ time python3 main.py --preload-path ./dat
<class 'pfio.cache.multiprocess_file_cache.MultiprocessFileCache'>
Namespace(dataset_len=1024, batchsize=32, num_workers=8, num_trials=5, preload_path='./dat', preserve_path=None, cache_type='multiprocess')
trial:  1, elapsed-time(all): 3.061 sec, ave-elapsed-time(img+label): 1.352 msec
trial:  2, elapsed-time(all): 2.045 sec, ave-elapsed-time(img+label): 1.967 msec
trial:  3, elapsed-time(all): 1.953 sec, ave-elapsed-time(img+label): 2.072 msec
trial:  4, elapsed-time(all): 1.981 sec, ave-elapsed-time(img+label): 2.062 msec
trial:  5, elapsed-time(all): 1.951 sec, ave-elapsed-time(img+label): 2.114 msec
real    0m11.728s
user    0m28.036s
sys     0m37.290s
$ time python3 main.py …
```
> Loader bench

- .pfnci/config.pbtxt
- .pfnci/script-old.sh
- .pfnci/script.sh
- .pfnci/test-old.sh
- .pfnci/test.sh
deadline exceeded happened and it's gradually longer
> Extend CI timeout

- pfio/v2/fs.py
- pfio/v2/s3.py
- tests/v2_tests/test_s3.py
Internally reported bug
The source of bug was to set class-bound member `.pid` in all `FS`-inherited classes and objects; for `S3`, `lazify` and `._check_forked()` always throw ForkedError as it's always returns class-bound member pid of parent process.
> Fix forkederror

- pfio/v2/hdfs.py
When accessing HDFS using pfio==2.0.0 with Python 3.9 environment, it immediately raises the following error.
```
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
return next(self.gen)
File "/usr/local/lib/python3.9/site-packages/pfio/v2/fs.py", line 293, in open_url
with from_url(dirname, **kwargs) as fs:
File "/usr/local/lib/python3.9/site-packages/pfio/v2/fs.py", line 350, in from_url
fs = _from_scheme(scheme, dirname, kwargs, bucket=parsed.netloc)
File "/usr/local/lib/python3.9/site-packages/pfio/v2/fs.py", line 365, in _from_scheme
fs = Hdfs(dirname, **kwargs)
File "/usr/local/lib/python3.9/site-packages/pfio/v2/hdfs.py", line 185, in __init__
self._fs = _create_fs()
File …
```
> `xml.etree.ElementTree.Element.getchildren` is abolished in python 3.9

- pfio/v2/s3.py
- tests/v2_tests/test_s3.py
It addresses #239 
This PR fixes the inconsistent behavior of `seek` when opening a file on S3.
```
with pfio.v2.open_url('s3://<bucket>/xxxx', 'rb') as f:
f.seek(0, os.SEEK_END)    # <------ It should move the cursor to the last byte of the stream, but it didn't
```
Fixing only the above case is enough to fix the issue reported in #239.
But for better transparency of pfio API with other types of filesystems, I updated the whole `seek` behavior to work identically to normal file-like objects returned by `open` (binary mode).
> [Ready] Fix `_ObjectReader.seek(0, os.SEEK_END)` case

- pfio/v2/hdfs.py
- tests/v2_tests/test_hdfs.py
In HDFS filesytem of the v2 API in `pfio==2.0.1`, `isdir` method returns `True` in case the specified path doesn't exist.
```bash
>>> fs = pfio.v2.from_url('hdfs:///user/<user>/')
>>> fs.isdir('this-does-not-exist')
True
```
This PR fixes it.
> Fix `pfio.v2.Hdfs.isdir` returns `True` to non-existent path

- pfio/v2/s3.py
- tests/v2_tests/test_s3.py
In the current pfio, `S3.rename` just copies the content into a new file, not removing the original one.
```python
>>> with pfio.v2.from_url('s3://suzuo/writer/test') as fs:
...     with fs.open('foo.dat', 'wb') as f:
...         f.write(b'hello world')
... 
...     print('ls before', list(fs.list()))
...     fs.rename('foo.dat', 'bar.dat')
...     print('ls after', list(fs.list()))
ls before ['foo.dat']
ls after ['bar.dat', 'foo.dat']
```
This is because that `rename` calls `remove` to delete the source object *with the key normalized*, which is then normalized again inside the `remove`. So `remove` tries to remove the specified key that does not exist instead of the original source one that we actually need to delete.
https://github.com/pfnet/pfio/blob/2.0.1/pfio/v2/s3.py#L523
This PR …
> Fix `S3.rename` didn't correctly remove the old file

- pfio/v2/hdfs.py
- pfio/v2/local.py
- pfio/v2/s3.py
- pfio/v2/zip.py
- tests/v2_tests/test_s3.py
This tries to fix #241 .
Main purpose is to provide buffering in S3 reader.
As left in the TODO comment [here](https://github.com/pfnet/pfio/blob/2.0.1/pfio/v2/s3.py#L359), `_ObjectReader` provided insufficient feature in order to use with [`io.BufferedReader`](https://docs.python.org/ja/3/library/io.html#io.BufferedReader).
In this PR I implemented `readall` and `readinto` methods that will be called from `BufferedReader`  in `_ObjectReader`, and make it subclass of `io.RawIOBase`.
This is basically same as how normal filesystem is handled in Python; `open("xxxx", "rb")` returns a `BufferedReader`, whose original stream is a `FileIO` (unbuffered raw stream for local files) object.
There are also several works included.
* Add kwargs `**_` trap to each filesystem.
* `S3` accepts …
> Buffered S3 reader

- pfio/v2/fs.py
- pfio/v2/hdfs.py
- pfio/v2/local.py
- pfio/v2/s3.py
- pfio/v2/zip.py
- tests/v2_tests/test_fs.py
- tests/v2_tests/test_hdfs.py
- tests/v2_tests/test_local.py
- tests/v2_tests/test_s3.py
- tests/v2_tests/test_zip.py
I'd like to have a discussion on adding the `create` option to `from_url`, which I propose a PoC implementation in this PR.
In the current `from_url` (specifically in local and HDFS filesytems), path to a non-existent directory is not accepted.
```python
>>> pfio.v2.from_url("/path/to/non/existent/dir")
ValueError: /path/to/non/existent/directory must be a directory
```
In this PR, I implemented `create` option to  each filesystem:
- `Local` and `HDFS`: When True and if the specified path doesn't exist, it creates the directory
- `S3`: Just ignores
- `Zip`: When True and the specified zip doesn't exist, it raises an error
This allows us to call `from_url` like this:
```python
>>> with pfio.v2.from_url("/path/to/non/existent/dir", create=True) as fs:
... 
>>> …
```
> Provide 'create' option in each filesystem (v2 API)

- pfio/__init__.py
With pfio==2.0.1, importing `pfio` automatically make `v2` and `__version__` visible.
```python
>>> import pfio
>>> pfio.__version__
'2.0.1'
>>> pfio.v2
<module 'pfio.v2' from '/home/xxx/xxx/pfio/pfio/v2/__init__.py'>
```
But in 2.1.0 this won't work.
```python
>>> import pfio
>>> pfio.__version__
File "<stdin>", line 1, in <module>
AttributeError: module 'pfio' has no attribute '__version__'
>>> pfio.version.__version__
File "<stdin>", line 1, in <module>
AttributeError: module 'pfio' has no attribute 'version'
>>> import pfio.version
>>> pfio.version.__version__
'2.1.0'
>>> pfio.v2
File "<stdin>", line 1, in <module>
AttributeError: module 'pfio' has no attribute 'v2'
>>> import …
```
> Fix import degradation

- pfio/v2/hdfs.py
- pfio/v2/local.py
This PR is to fix the issue that `from_url(xxx, create=True)` implemented in #245 *can* fail in parallel processing situation.
```python
import pfio
pfio.v2.from_url('non-existent-dir', create=True)
```
```bash
> mpiexec -n 4 python from_url.py
File "from_url.py", line 5, in <module>
pfio.v2.from_url('non-existent-dir', create=True)
File "/usr/local/lib/python3.8/site-packages/pfio/v2/fs.py", line 359, in from_url
fs = _from_scheme(scheme, dirname, kwargs, bucket=parsed.netloc)
File "/usr/local/lib/python3.8/site-packages/pfio/v2/fs.py", line 371, in _from_scheme
fs = Local(dirname, **kwargs)
File "/usr/local/lib/python3.8/site-packages/pfio/v2/local.py", line 56, in __init__
os.makedirs(self._cwd)
File "/usr/local/lib/python3.8/os.py", line 223, in …
```
> Prevent race condition for from_url(create=True) in case of parallel processing

- pfio/cache/file_cache.py
- pfio/cache/mmap_file_cache.py
- pfio/cache/multiprocess_file_cache.py
- tests/cache_tests/test_cache.py
Addresses #261 . 
The XDG standard says
> $XDG_CACHE_HOME defines the base directory relative to which user-specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used.
> Use XDG standard for cache path

- pfio/cache/__init__.py
- setup.py
- tests/cache_tests/test_cache.py
When we use `Cache.get_and_cache()` for `numpy.ndarray`, we get the following error:
```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
This PR fixes the above issue.
> Fix Cache for numpy

- pfio/v2/fs.py
- pfio/v2/hdfs.py
- pfio/v2/local.py
- pfio/v2/s3.py
- pfio/v2/zip.py
- tests/v2_tests/test_fs.py
To address https://github.com/pfnet/pfio/issues/260 , a new argument `reset_on_fork` is introduced to each FS object constructor. If it is turned on, internal method `_check_fork()` calls a newly introduced abstract method `_reset(self)` . This abstraction enables transparent forking in any situation - be it PyTorch DataLoader or multiprocessing, or "forkserver" enabled.
Classes `S3` and `Hdfs` now do not pickle their internal unpickable, e.g. boto connection or Hdfs connection. If they're forked, they're forced to reset the connection.
It also worked well with PyTorch DataLoader like this:
```python
import time
import os
import multiprocessing
import torch
from pfio.v2 import from_url
class Dataset:
def __init__(self):
self.s3 = from_url('s3://bucket/', reset_on_fork=True)
def …
```
> Introduce reset_on_fork argument

- pfio/v2/s3.py
- tests/v2_tests/test_s3.py
> Fix `BufferedReader` error caused by opening an empty file in S3 in "rb" mode

- docs/source/reference.rst
- pfio/cache/__init__.py
- pfio/cache/sparse_file.py
- pfio/v2/s3.py
- pfio/v2/zip.py
- tests/cache_tests/test_sparse_file.py
- tests/v2_tests/test_s3_zip.py
- tests/v2_tests/test_zip.py
With adding `local_cache=True` keyword to opening a zip FS e.g. using `from_url()` , a local cache file is created in a path (by default, `~/.cache/pfio/` ). The cache file is a named temporary file, but potentially, it can easily be persisted locally. It costs the local disk space, but the amount is just as same as the total amount of data transferred over the network to the client.
This will be a major step toward working around #271, as well as improving latency on reading a file from remote file system such as S3.
You can see the difference of space consumed like this:
```
$ ls -lh  ~/.cache/pfio/tmpjwvpycrg
-rw------- 1 kota kota 155G Jun  6 12:29 /home/kota/.cache/pfio/tmpjwvpycrg
$ du -h  ~/.cache/pfio/tmpjwvpycrg
184M    /home/kota/.cache/pfio/tmpjwvpycrg
```
- For threads: while …
> Sparse file local cache

- .pfnci/config.pbtxt
- pfio/cache/sparse_file.py
- tests/cache_tests/test_sparse_file.py
Can be used like
```python
with from_url("s3://path/to/foo.zip", local_cache=True, reset_on_fork=True,
cache_size_limit=4096*4096) as s3:
s3.open.read()
```
> Limit the sparse cache size

- .pfnci/config.pbtxt
- .pfnci/docker/Dockerfile
- .pfnci/docker/Makefile
- .pfnci/test-old.sh
- .pfnci/test.sh
- setup.py
- tox.ini
Master CI is failing like this:
```
py37: commands[1]> flake8 pfio
/repo/.tox/py37/lib/python3.7/site-packages/pep8.py:110: FutureWarning: Possible nested set at position 1
EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
pfio/cache/__init__.py:65:1: F401 'MultiprocessSparseFileCache' imported but unused
File "/repo/.tox/py37/bin/flake8", line 8, in <module>
sys.exit(main())
File "/repo/.tox/py37/lib/python3.7/site-packages/flake8/main.py", line 36, in main
report = flake8_style.check_files()
File "/repo/.tox/py37/lib/python3.7/site-packages/flake8/engine.py", line 181, in check_files
return self._retry_serial(self._styleguide.check_files, paths=paths)
File "/repo/.tox/py37/lib/python3.7/site-packages/flake8/engine.py", line 172, in …
```
> Flake8 skip for Python 3.7

- pfio/cache/http_cache.py
This PR refines HTTPCache to support fault-tolerance and multiprocessing with fork-server execution model.
- https://github.com/pfnet/pfio/commit/8ab92dfde2a0bcac909eb298b6bf732df50bc122
- Reports error (i.e. unexpected HTTP status code or exception) to user instead of stop working
- https://github.com/pfnet/pfio/commit/36b1df82de8a0fe6f4547580c007d0fbeb4ee9b4
- We can expect that the HTTP backend doesn't return many redirect or errors, so we limit the number of retries to one.
- https://github.com/pfnet/pfio/commit/b138d89c923259dff13837bc572792e991d6f33c
- We can expect that the HTTP backend processes requests faster I/O, so we shorten the timeout.
- https://github.com/pfnet/pfio/commit/72c9da444218912ccd652881f0cf2067bb382cfe
- multiprocessing with fork-server execution model requires …
> Refine pfio.cache.HTTPCache

- pfio/v2/zip.py
- setup.py
- tests/v2_tests/test_s3_zip.py
Current PFIO doesn't support S3 + zipfile on fork-server based multiprocessing execution model.
This model requires parameters given to Process should be pickled to move object from child to parent, who has responsibility to fork an new process.
https://github.com/pfnet/pfio/pull/292/commits/dffff08c83c3fb52147ab53029d212625828a1c3 solves this issue by avoiding pickling of fileobj and zipobj, then after fork, it will be re-created by zip and S3's _reset() functions.
> S3 + zipfile on fork-server multiprocessing

- docs/source/reference.rst
- pfio/cache/sparse_file.py
- pfio/v2/fs.py
- pfio/v2/hdfs.py
- pfio/v2/local.py
- pfio/v2/s3.py
- pfio/v2/zip.py
- tests/v2_tests/test_fs.py
- tests/v2_tests/test_s3.py
- tests/v2_tests/test_s3_zip.py
- tests/v2_tests/test_zip.py
Fixes https://github.com/pfnet/pfio/issues/296
- Removed `reset_on_fork` parameter from all FS implementations
- ~Removed `ForkedError` because we don't need it now~
- Added `reset_on_fork` parameter check on `from_url` to notify the deprecation
I've found that, in zip + SparseFileCache case, we always use MPCachedWrapper instead of CachedWrapper because we don't have prior information of fork existence by `reset_on_fork` parameter. This may introduce performance decrease by `flock(2)`.
> Remove reset_on_fork parameter

- docs/source/reference.rst
Just fixing the reference.
Before | After
-- | --
https://pfio.readthedocs.io/en/latest/reference.html#cache-api
> Fix broken sphinx reference

- pfio/v2/hdfs.py
- setup.py
- tests/v2_tests/test_hdfs.py
- tox.ini
After 2.6.0, to use HDFS connector, do `pip install pfio[hdfs]` .
> Make HDFS optional

- pfio/v2/fs.py
- pfio/v2/local.py
- pfio/v2/pathlib.py
- tests/v2_tests/test_pathlib.py
Fixed `Path.glob()` for compatibility with standard `pathlib.Path`.
* Made it hierarchy aware. Before `Path.glob("*")` returned all the entries in a recursive manner.
* Fixed so that the base path (on which the glob operation is performed) is included in the returned paths. Before they were relative to the base path.
* Omit trailing `/` for returned directory paths.
Along with that, I did several related changes:
* Refactored internal data of the `Path` class. Specifically, `_root` is merged to `_parts`.
* Added `Path.iterdir()`, `Path.parts` and `Path.root` for compatibility with standard `pathlib.Path`.
> Fix Path.glob for compatibility with standard pathlib.Path

- tests/v2_tests/test_fs.py
- tests/v2_tests/test_s3_zip.py
Current master branch doesn't pass the flake8 test due to its automatic update. This PR fixes code to pass flake8 v6.1.0 test.
```
$ flake8 pfio tests                                                                                                                             
tests/v2_tests/test_fs.py:87:16: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`                                                                         
tests/v2_tests/test_s3_zip.py:29:48: E231 missing whitespace after ','                                                                                                                                           
tests/v2_tests/test_s3_zip.py:160:48: E231 missing whitespace after ','  
```
> Fix flake8 v6.1.0

- pfio/cache/http_cache.py
Based on https://github.com/pfnet/pfio/pull/317 work, but cherry-picked
I profiled HTTPConnector's performance by using [cProfile](https://docs.python.org/3/library/profile.html) and [snakeviz](https://jiffyclub.github.io/snakeviz/). I found that urllib3's HTTP request is not optimized for sending requests to the same host.
Previous: 
The given url is parsed many times to get appropriate connection from the connection pool. The url parse is actually just execution of regexp, but from the perspective of small file use case (latency-neck), it should not be happened many times.
This PR:
I re-implemented connection pool for sending requests to the same host. By this, we can see the performance improvement (we're using more time in `recvinto` relatively, so it means the latency is reduced). …
> Rewrite HTTPConnector by http.client

- pfio/v2/zip.py
- tests/v2_tests/test_zip.py
When I tested https://github.com/pfnet/pfio/pull/316 PR with the ImageNet-1K dataset, I found that Zip(FS).stat() performance is pretty bad
because:
- list all filenames in the zip archive twice in the worst case
- check filename is correct or not by linear search twice in the worst case
Therefore, I'd like to cache filenames with the `set` structure to avoid redundant construction and improve search performance if the archive is opened in read-only mode.
> Avoid calling zip.namelist many times

- pfio/v2/_utils.py
- pfio/v2/fs.py
- pfio/v2/hdfs.py
- pfio/v2/local.py
- pfio/v2/s3.py
- pfio/v2/zip.py
- tests/v2_tests/test_hdfs.py
- tests/v2_tests/test_local.py
- tests/v2_tests/test_s3.py
- tests/v2_tests/test_zip.py
It would be convenient if some information was included in `repr`.
```
<pfio.v2.local.Local object at 0x7f6b09c7d120>
```
↓
```
pfio.v2.local.Local(cwd='/')
```
> Add __repr__ to FS classes

- pfio/v2/zip.py
In 1/2 favor of https://github.com/pfnet/pfio/issues/311 .
> Deprecate sparse file cache in 2.7 (and will be deleted in 2.8)

- docs/source/reference.rst
- pfio/v2/__init__.py
- pfio/v2/fs.py
- pfio/v2/hdfs.py
- pfio/v2/http_cache.py
- pfio/v2/local.py
- pfio/v2/s3.py
- pfio/v2/zip.py
- tests/v2_tests/test_fs.py
- tests/v2_tests/test_http_cache.py
This PR adds HTTPCachedFS, a wrapper to hook read operations and cache the content with HTTPConnector. HTTPCachedFS wrapper hooks read operations, then try HTTPCache to retrieve its content. The underlying FS will not be called if the data is in the cache. Other operations like write and list will be transferred to the underlying FS.
In order to introduce such a feature, I added `_canonical_name(path)` to FS interface and implementations. `_canonical_name(path)` returns `path` with filesystem information to distinguish Local("abc")._canonical_name("somefile") and S3("abc")._canonical_name("somefile"). S3 and HDFS will encode its endpoint to the path to distinguish multiple endpoints (like AWS's S3 and some S3 compatible storage systems).
Users can enable HTTPCache transparently by …
> HTTPCachedFS

- pfio/v2/s3.py
Current code on `master` fails to handle large files on AWS S3 in 2 ways:
1. When performing multi-part uploading, the md5 given to `upload_part` is hexadecimal, but base64 is expected.
2. When calling `S3.rename` with a source object larger than 5GB, it fails due to limitations of `copy_object`.
While issue 1. is a straightforward fix. Solving issue 2. requires using multi-part copying, which (in my understanding) makes `rename` no longer atomic for large files. Considering `rename` is often used for its atomicity, I'm not sure whether this solution is best, and would be happy to get feedback.
> S3 support for large files

- .readthedocs.yaml
- README.md
Please check the build success at https://readthedocs.org/projects/pfio/builds/ .
> Fix document build fail and add status badge

- setup.py
- tests/v2_tests/test_custom_scheme.py
- tests/v2_tests/test_fs.py
- tests/v2_tests/test_http_cache.py
- tests/v2_tests/test_pathlib.py
- tests/v2_tests/test_s3.py
- tests/v2_tests/test_s3_zip.py
`moto` version 5 renames `moto.mock_s3` to `moto.mock_aws`.
https://docs.getmoto.org/en/latest/docs/getting_started.html
> update: moto v5

- .github/workflows/python-package.yml
- setup.py
- tox.ini
> Support python 3.12

- pfio/v2/pathlib.py
- tests/v2_tests/test_pathlib.py
This PR improves compatibility between `pfio.v2.pathlib.Path` and `pathlib.Path`.
The key differences between this PR and current impl./`pathlib.Path` as follows.
- many methods raise `NotImplementedError` because they require unsupported features of `FS`
- provides `scheme` property for `as_uri` (will move to `FS`)
- `as_uri` returns `file`, `s3`, `hdfs` or custom scheme URI dependent on `fs` and `scheme`
- `stat` returns `pfio.v2.FileStat` instead of `os.stat_result`
> Path: more compatibility with pathlib.Path

- .github/workflows/python-package.yml
Trying to address CI failure: https://github.com/pfnet/pfio/pull/336#issuecomment-2060060780
> Pick out document build at CI

- docs/source/tips.rst
- mypy.ini
- pfio/v2/_profiler.py
- pfio/v2/local.py
- setup.py
- tests/v2_tests/test_local.py
- tox.ini
This PR resolves the `Local` task in #258 
> [!NOTE]
> To enable tracing, `trace=True` must be added during `Local()` initialization (or `from_url()`).
Sample program to check tracing
```python
import json
import pytorch_pfn_extras as ppe
from pfio.v2 import Local, Path, from_url
@ppe.profiler.record_function("my_tag_2", trace=True)
def my_run2(x):
pass
def my_run1(x):
pass
def p():
tracer = ppe.profiler.get_tracer()
tracer.clear()
with ppe.profiler.record("my_tag_1", trace=True):
my_run1('hoge')
for i in range(4):
my_run2("far")
dir = 0
fil = 0
with Local(trace=True) as fs:
for f in fs.list():
if fs.isdir(f.strip()):
dir += 1
continue
fil += 1
len(fs.open(f).read())
print(fil, "files", dir, "dirs")
dict = tracer.state_dict()
keys = [event["name"] for event in …
```
> Support PPE profiling for `Local`

- pfio/v2/s3.py
- tests/v2_tests/test_custom_scheme.py
- tests/v2_tests/test_s3.py
Allow users to configure `botocore.{connect,read}_timeout` in `pfio.v2.S3`. Support both the ways via the custom scheme or via directly passing the initializer (`from_url`, `pfio.v2.S3`) like the below:
**a) via the custom scheme**
```ini
[baz]
scheme = s3
endpoint = https://s3.example.com
aws_access_key_id=hoge
aws_secret_access_key=$HOME
connect_timeout=300
read_timeout=120
```
**b) via the initializer (`from_url`)** ... from a test code
```python
def test_s3_init_with_timeouts(s3_fixture):
with from_url('s3://test-bucket/base',
connect_timeout=300,
read_timeout=120) as s3:
assert isinstance(s3, S3)
assert (s3.botocore_config['connect_timeout'] == 300)
assert (s3.botocore_config['read_timeout'] == 120)
```
> Make `botocore.config.Config.{connect,read}_timeout` configurable

- pfio/v2/s3.py
- tests/v2_tests/test_s3.py
This PR resolves the `S3` task in #258 
Sample program to check tracing
```
import json
import pytorch_pfn_extras as ppe
from pfio.v2 import S3, Path, from_url
def p():
tracer = ppe.profiler.get_tracer()
tracer.clear()
fil = 0
with from_url('pfs1://cluster-tutorial/', trace=True) as fs:
assert isinstance(fs, S3)
for f in fs.list(recursive=True):
if f == "imagenet-classification.zip":
continue
with fs.open(f, 'rb') as fp:
tmp = fp.read()
fil += 1
if fil > 10:
break
print(fil, "files")
dict = tracer.state_dict()
keys = [event["name"] for event in json.loads(dict["_event_list"])]
print(keys)
w = ppe.writing.SimpleWriter(out_dir="")
tracer.initialize_writer("trace_s3.json", w)
tracer.flush("trace_s3.json", w)
p()
```
output
```
11 files
['pfio.v2.S3:list-0', 'pfio.v2.S3:open', …
```
> Support PPE profiling for `S3`

- pfio/v2/zip.py
- tests/v2_tests/test_s3_zip.py
- tests/v2_tests/test_zip.py
This PR resolves the `Zip` task in #258 
Sample program to check tracing
```python
import json
import pytorch_pfn_extras as ppe
from pfio.v2 import Local, Path, from_url
from pfio.testing import ZipForTest
def p():
tracer = ppe.profiler.get_tracer()
tracer.clear()
zipfilename = "test.zip"
data = dict(
foo = b'foo',
bar = b'bar',
foobar = b'foobar',
)
file = ZipForTest(zipfilename, data)
with from_url(zipfilename, trace=True) as fs:
for name in fs.list(recursive=True):
with fs.open(name, mode='rb') as fp:
tmp = fp.read()
assert file.content(name) == tmp
state = tracer.state_dict()
keys = [event["name"] for event in json.loads(state["_event_list"])]
print(keys)
w = ppe.writing.SimpleWriter(out_dir="")
tracer.initialize_writer("trace_zip.json", w)
tracer.flush("trace_zip.json", w)
p()
``` …
> Support PPE profiling for `Zip`

- .github/workflows/python-package.yml
- .gitignore
This reverts commit c4dff7cd3927cef40ae100787c5d1c60546711f5.
The CI invoked from external collaborators is failing, and we need to carefully redesign the CI and driver implementation, so we will revert the CI support for GCS once.
> Revert "Settings for workload identity federation (gcs) (#346)"

- tox.ini
relax the line length restriction as the implementation of the profiler often leads to deep indent
> update max line length

- pfio/cache/http_cache.py
- pfio/cache/multiprocess_file_cache.py
- pfio/v2/fs.py
- pfio/v2/http_cache.py
- tests/cache_tests/test_cache.py
- tests/v2_tests/test_http_cache.py
This PR resolves the `CachedHttpFs` / `HttpCache` task in #258 
Sample program to check tracing
```python
import json
import tempfile
import pytorch_pfn_extras as ppe
from pfio.v2 import HTTPCachedFS, Local
from pfio.cache import HTTPCache
from pfio.testing import make_http_server
def cache_httpcache():
filename = "cache_httpcache.json"
tracer = ppe.profiler.get_tracer()
with make_http_server() as (httpd, port):
http_cache = f"http://localhost:{port}/"
cache = HTTPCache(1, http_cache,
do_pickle=True, trace=True)
cache.put(0, b"foo")
assert b"foo" == cache.get(0)
dict = tracer.state_dict()
keys = [event["name"] for event in json.loads(dict['_event_list'])]
print(keys)
writer = ppe.writing.SimpleWriter(out_dir="")
tracer.initialize_writer(filename, writer)
tracer.flush(filename, writer)
def …
```
> Support PPE profiling for HTTPCache / HTTPCachedFS

- .github/workflows/python-package.yml
- README.md
- setup.py
- tox.ini
Addresses: https://github.com/pfnet/pfio/issues/310
> Drop Python 3.8 as of PEP-569
