pfnet/pfio

- setup.py
I can't reproduce the issue we faced at https://github.com/chainer/chainer/pull/4534 .
> Remove NumPy workaround

- .pfnci/config.pbtxt
- .pfnci/docker/install.sh
- .pfnci/script.sh
- .pfnci/test.sh
This commit fixes a bug in pfnci script.
In the previous CI, there are two tests performed, tox for pytest and
sphinx build. The CI script fails to combine all the return value
of the test commands, hence the CI status only show the status of the
sphinx build.
In this commit, the return status of both tests are combined and returned.
>  Fix bugs in pfnci script

- docs/source/design.rst
> Remove an unnecessary word

- chainerio/__init__.py
- chainerio/_context.py
- chainerio/_typing.py
- chainerio/cache/__init__.py
- chainerio/container.py
- chainerio/containers/zip.py
- chainerio/filesystem.py
- chainerio/filesystems/hdfs.py
- chainerio/io.py
- setup.py
> Add workaround for old python

- chainerio/cache/file_cache.py
Also I updated some docs of `FileCache`.
> Remove mutable default argument

- .pfnci/test.sh
- docs/source/conf.py
- setup.py
This commit changes the sphinx theme to match with Chainer.
> Change theme of docs

- .pfnci/docker/Dockerfile
- .pfnci/docker/Makefile
- .pfnci/docker/install.sh
- .pfnci/script.sh
- .pfnci/test.sh
- pfio/cache/multiprocess_file_cache.py
- setup.py
- tox.ini
Fix the broken window.
- Drop 3.5
- Add 3.8 and 3.9
- Fix pyarrow version to 3.0.0
- Change testing image to GCR-hosted new one based on Ubuntu 20.04
> Fix update python

- pfio/cache/__init__.py
- setup.py
- tests/cache_tests/test_file_cache.py
- tox.ini
We don't support Python 2 any more.
> Remove six

- pfio/v2/hdfs.py
- tests/v2_tests/test_hdfs.py
- tests/v2_tests/test_local.py
Fix several bugs during drafting V2 API.
> Cleanup tests

- pfio/cache/file_cache.py
- pfio/cache/multiprocess_file_cache.py
> Document NoNFS

- pfio/v2/s3.py
- tests/v2_tests/test_s3.py
> Implement multipart upload to S3 ObjectWriter

- pfio/v2/s3.py
- tests/v2_tests/test_fs.py
Addresses #168 , but it seems moto doesn't support range read of get_object.
> Make s3 read seekable

- pfio/v2/hdfs.py
- setup.py
- tests/v2_tests/test_hdfs.py
Addresses https://github.com/pfnet/pfio/issues/139 .
> Pyarrow new api

- pfio/v2/s3.py
- tests/v2_tests/test_fs.py
Backport https://github.com/pfnet/pfio/pull/188 to 1.4.
> Fix text mode readlines

- pfio/v2/s3.py
- tests/v2_tests/test_s3.py
> Fix BufferedIOBase requires readinto() implemented

- docs/source/v2.rst
- pfio/v2/__init__.py
- pfio/v2/pathlib.py
- pfio/v2/s3.py
- tests/v2_tests/test_pathlib.py
- tests/v2_tests/test_s3.py
Initial implementation that addresses #192 .
> Add pathlib-like API supporting glob and path concatination

- pfio/v2/local.py
- pfio/v2/pathlib.py
- tests/v2_tests/test_pathlib.py
> Add .parent, .name, .suffix

- docs/requirements.txt
- setup.py
Retrying https://github.com/pfnet/pfio/pull/205
> RTFD build fix

- pfio/v2/fs.py
> Make kwargs available in open_url too

- pfio/v2/pathlib.py
- tests/v2_tests/test_pathlib.py
> Fix pathlib return value

- docs/source/index.rst
- docs/source/tips.rst
Addresses https://github.com/pfnet/pfio/issues/262 .
> Add tips on shutil.copyfileobj()

- .pfnci/docker/Dockerfile
- .pfnci/test-old.sh
- .pfnci/test.sh
- setup.py
Addresses https://github.com/pfnet/pfio/issues/226 .
> Drop Python 3.6

- .gitignore
- pfio/cache/sparse_file.py
- pfio/v2/s3.py
- pfio/v2/zip.py
Addressing 1/2 of https://github.com/pfnet/pfio/issues/276 .
> Thread safety

- docs/source/reference.rst
- pfio/cache/__init__.py
- pfio/cache/sparse_file.py
- pfio/v2/fs.py
- pfio/v2/s3.py
- pfio/v2/zip.py
- tests/cache_tests/test_sparse_file.py
- tests/v2_tests/test_s3_zip.py
Addresses 2/2 of https://github.com/pfnet/pfio/issues/276 . Works with pfio.v2.Zip, too.
> Multiprocessing-safe sparse file cache

- pfio/v2/fs.py
- pfio/v2/hdfs.py
- pfio/v2/local.py
- pfio/v2/s3.py
- pfio/v2/zip.py
- tests/v2_tests/test_fs.py
Partially addresses https://github.com/pfnet/pfio/issues/154
> detail=True option for listing directory or prefix

- pfio/v2/zip.py
- tests/v2_tests/test_zip.py
Addresses 2/2 of https://github.com/pfnet/pfio/issues/154
> detail=True option for listing zip internals

- pfio/cache/sparse_file.py
It is actually thread safe now
> Update documentation of sparse file cache

- mypy.ini
- pfio/cache/file_cache.py
- pfio/cache/sparse_file.py
- pfio/testing/__init__.py
- pfio/v2/fs.py
- pfio/v2/hdfs.py
- pfio/v2/local.py
- pfio/v2/s3.py
- pfio/v2/zip.py
- setup.py
- tox.ini
Addresses https://github.com/pfnet/pfio/issues/303 .
> Introduce mypy type check

- .github/workflows/python-package.yml
- setup.py
- tox.ini
Addresses: #353
Introduce Python 3.13 into CI and their environments, and tox.ini.
> Support Python 3.13
